name: Post
on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed
    branches:
      - 'release/**'

jobs:
  post:
    name: Post
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo 123
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
